/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.modelo;

import ec.edu.ups.controlador.ControladorPersona;
import javax.swing.JOptionPane;

/**
 *
 * @author Domenica Cañizares
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form otro
     */
    private ControladorPersona contPer;
    
    private Crear crearPer;
    private Buscar buscarPer;
    private Modificar modPer;
    private Eliminar eliPer;
    private Listar listarPer;

    public Menu() {
        initComponents();
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCrear = new javax.swing.JMenuItem();
        itemBuscar = new javax.swing.JMenuItem();
        itemMod = new javax.swing.JMenuItem();
        itemEli = new javax.swing.JMenuItem();
        itemListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Persona");

        itemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemCrear.setText("Crear");
        itemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearActionPerformed(evt);
            }
        });
        jMenu1.add(itemCrear);

        itemBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemBuscar.setText("Buscar");
        itemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(itemBuscar);

        itemMod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itemMod.setText("Modificar");
        itemMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModActionPerformed(evt);
            }
        });
        jMenu1.add(itemMod);

        itemEli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        itemEli.setText("Eliminar");
        itemEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliActionPerformed(evt);
            }
        });
        jMenu1.add(itemEli);

        itemListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemListar.setText("Listar");
        itemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarActionPerformed(evt);
            }
        });
        jMenu1.add(itemListar);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearActionPerformed

        String x = crearPer.x;

        try {

            if (x == null) {

                if (crearPer == null || crearPer.isVisible() == false) {

                    crearPer = new Crear(contPer);
                    DesktopPane.add(crearPer);

                }

            } else {

                JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error " + ex.toString());
            System.err.println("Error " + ex.toString());

        }


    }//GEN-LAST:event_itemCrearActionPerformed

    private void itemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarActionPerformed
        
        String x = buscarPer.x;

        try {

            if (x == null) {

                if (buscarPer == null || buscarPer.isVisible() == false) {

                    buscarPer = new Buscar(contPer);
                    DesktopPane.add(buscarPer);

                }

            } else {

                JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error " + ex.toString());
            System.err.println("Error " + ex.toString());

        }
        
    }//GEN-LAST:event_itemBuscarActionPerformed

    private void itemModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModActionPerformed
        
        String x = modPer.x;

        try {

            if (x == null) {

                if (modPer == null || modPer.isVisible() == false) {

                    modPer = new Modificar(contPer);
                    DesktopPane.add(modPer);

                }

            } else {

                JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error " + ex.toString());
            System.err.println("Error " + ex.toString());

        }
        
    }//GEN-LAST:event_itemModActionPerformed

    private void itemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarActionPerformed
        
        String x = listarPer.x;

        try {

            if (x == null) {

                if (listarPer == null || listarPer.isVisible() == false) {

                    listarPer = new Listar(contPer);
                    DesktopPane.add(listarPer);

                }

            } else {

                JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error " + ex.toString());
            System.err.println("Error " + ex.toString());

        }
        
    }//GEN-LAST:event_itemListarActionPerformed

    private void itemEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliActionPerformed
        
        String x = eliPer.x;

        try {

            if (x == null) {

                if (eliPer == null || eliPer.isVisible() == false) {

                    eliPer = new Eliminar(contPer);
                    DesktopPane.add(eliPer);

                }

            } else {

                JOptionPane.showMessageDialog(this, "La ventana ya esta abierta");

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error " + ex.toString());
            System.err.println("Error " + ex.toString());

        }
        
    }//GEN-LAST:event_itemEliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem itemBuscar;
    private javax.swing.JMenuItem itemCrear;
    private javax.swing.JMenuItem itemEli;
    private javax.swing.JMenuItem itemListar;
    private javax.swing.JMenuItem itemMod;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
